sudo: required

language: ruby

services:
        - docker

before_install:
        - docker build --tag=shaoguangleo/centos:latest .
        - docker run -it shaoguangleo/centos:latest
        - docker ps -a
